#!/bin/sh

make
./puredata | tr ',' '\n' | tr -d '[]' > lines
cat <<EOF > lines.plot
set terminal png
set output "plot.png"
plot "lines" with lines
EOF
#gnuplot lines.plot
#xdg-open ./plot.png
cat lines | lua -e '
for s in io.stdin:lines() do
   local n = tonumber(s)
   io.stdout:write(string.char(n // 256), string.char(n % 256))
end' > binario
rm output.wav
ffmpeg -f u16be -ar 32000 -ac 1 -i binario output.wav
mplayer output.wav
